
class student():
    #attributes
    student_name="amit learning"
    student_age=10
    student_GPA=3.99
    student_gender="male"
    #methods
    def student_info(x):
        print("hello ")
        ""'''print(f"student name: {student_name}") 
        print(f"student age: {student_age}")
        print(f"student GPA : {student_GPA}")
        print(f"student gender : {student_gender}")'''""
#instance
s1=student()
#edit attribute
#s1.student_name=" Toka Sherif "
#print attribute
#print(s1.student_name)
print(s1.student_info())